### ISSUE TITLE
Issue while implementing this with nativescript . 

### ISSUE THREAD

**Issue by chandansutradhar2** [ngx-translate/core#696]
I  am facing this error., while implementing ngx-translate for localization.
Im using Nativescript 3 with angular 4
https://github.com/ngx-translate/core

The error displayed is "
ns-renderer: ERROR BOOTSTRAPPING ANGULAR
JS: ns-renderer: Not implemented!
JS:
JS: Error: Not implemented!
JS: at NativeScriptDomAdapter.getCookie (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules/nativescript-angular/dom-adapter.js:155:75) [angular]
JS: at CookieXSRFStrategy.configureRequest (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/http.umd.js:1376:77) [angular]
JS: at XHRBackend.createConnection (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/http.umd.js:1425:28) [angular]
JS: at httpRequest (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/http.umd.js:1833:20) [angular]
JS: at Http.request (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/http.umd.js:1943:34) [angular]
JS: at Http.get (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/http.umd.js:1957:21) [angular]
JS: at TranslateHttpLoader.getTranslation (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/http-loader.umd.js:110:26)
[angular]
JS: at TranslateService.getTranslation (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/core.umd.js:377:55) [angular]
JS: at TranslateService.retrieveTranslations (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/core.umd.js:363:87) [angular]
JS: at TranslateService.setDefaultLang (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/core.umd.js:304:28) [angular]
JS: at new AppComponent (file:///data/data/samayainfotech.freeinvoice/files/app/app.component.js:15:19) [angular]
JS: at createClass (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/core.umd.js:11009:26) [angular]
JS: at createDirectiveInstance (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/core.umd.js:10834:37) [angular]
JS: at createViewNodes (file:///data/data/samayainfotech.freeinvoice/files/app/tns_modules//bundles/core.umd.js:
"
.......

My app.module.ts looks like this
import { NgModule, NgModuleFactoryLoader, NO_ERRORS_SCHEMA } from "";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { NSModuleFactoryLoader } from "nativescript-angular/router";
import {HttpModule,Http} from '';
import {TranslateModule, TranslateLoader,TranslatePipe,TranslateService} from '';
import {TranslateHttpLoader} from '';

import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";
import {SharedData} from './model/data.model';
import {MessageService} from './message/message.service';

export function HttpLoaderFactory(http: Http) {
return new TranslateHttpLoader(http,/app/i18n/,.json);
}

@NgModule({
bootstrap: [
AppComponent
],
imports: [
HttpModule,
NativeScriptModule,
AppRoutingModule,
TranslateModule.forRoot({
loader: {
provide: TranslateLoader,
useFactory: (HttpLoaderFactory),
deps: [Http]
}
})
],
declarations: [
AppComponent
],
providers: [
{ provide: NgModuleFactoryLoader, useClass: NSModuleFactoryLoader},
SharedData,MessageService
],
schemas: [
NO_ERRORS_SCHEMA
],
})
export class AppModule {
constructor(){
console.log('app module loaded sucessfully');
}
}

and my app.component.ts consists of

import { Component } from "";
import {SharedData} from './model/data.model';
import * as firebase from 'nativescript-plugin-firebase';
import {RouterExtensions} from 'nativescript-angular/router';
import {hasKey,remove} from "application-settings";
import {TranslateService,TranslatePipe} from '';

@component({
selector: "ns-app",
templateUrl: "app.component.html"
})
export class AppComponent {
firstInstall:boolean;

constructor(private router:RouterExtensions,private data:SharedData,translate: TranslateService){
    console.log('App component loaded');
    debugger;
    console.dir(translate);
    translate.setDefaultLang('de');
    
    firebase.init({
        // Optionally pass in properties for database, authentication and cloud messaging,
        // see their respective docs.
      }).then(
        (instance) => {
          console.log("firebase.init done");
        },
        (error) => {
          console.log("firebase.init error: " + error);
        }
      );

    // if(hasKey('firstInstall')){
    //     //show the first install screen
    //     this.router.navigate(['/home']);            
    // }else{
    //     debugger;
    //     this.router.navigate(['firstinstallui']);
    // }
}
}

Package.json consists of
{
"description": "NativeScript Application",
"license": "SEE LICENSE IN ",
"readme": "NativeScript Application",
"repository": "",
"nativescript": {
"id": "samayainfotech.freeinvoice",
"tns-android": {
"version": "3.3.0-2017-9-29-1"
}
},
"scripts": {
"lint": "tslint "app/**/*.ts""
},
"dependencies": {
"": "4.2.5",
"": "4.2.5",
"": "4.2.5",
"": "4.2.5",
"": "4.2.5",
"": "4.2.5",
"": "4.2.5",
"": "4.2.5",
"": "^8.0.0",
"": "^0.1.0",
"angular2-signaturepad": "^2.6.1",
"nativescript-accordion": "^5.0.2",
"nativescript-angular": "4.2.0",
"nativescript-autocomplete": "^1.0.0",
"nativescript-cardview": "^2.0.2",
"nativescript-contacts": "^1.5.3",
"nativescript-couchbase": "^1.0.18",
"nativescript-drawingpad": "^2.1.0",
"nativescript-drop-down": "^3.1.1",
"nativescript-feedback": "^1.0.6",
"nativescript-floatingactionbutton": "^3.0.1",
"nativescript-imagepicker": "^3.0.7",
"nativescript-plugin-firebase": "^4.1.1",
"nativescript-pro-ui": "3.1.2",
"nativescript-theme-core": "1.0.4",
"reflect-metadata": "0.1.10",
"rxjs": "5.4.3",
"tns-core-modules": "3.2.0",
"zone.js": "0.8.17"
},
"devDependencies": {
"babel-traverse": "6.4.5",
"babel-types": "6.4.5",
"babylon": "6.4.5",
"codelyzer": "3.2.0",
"lazy": "1.0.11",
"nativescript-dev-sass": "1.3.2",
"nativescript-dev-typescript": "0.5.0",
"node-sass": "4.5.3",
"tslint": "5.7.0",
"typescript": "2.5.2"
}
}

Any help would be appreciated.

**Comment by giorgiopiatti** [comment]
The same issue happened to me, when accessing to the methods of the TranslateService class the app crashes. Before that there aren't any errors.

**Comment by giorgiopiatti** [comment]
Sorry I've forgotten to say that this problem happens with the last version of nativescript and angular.
The plugin version that reproduce this issue are the  8.0.0 but also the 7.0.0, with the others versions I haven't made any tests.

**Comment by giorgiopiatti** [comment]
@chandansutradhar2 This error happens because in Nativescript you must import the `NativeScriptHttpModule` in order to use Http .

**Comment by renestalder** [comment]
I used the correct NativeScriptHttpModule, also added NativeScriptHttpClientModule. No luck getting it working.

Followed the comment here and got it working with version 8.0.0.
https://github.com/ngx-translate/core/issues/595#issuecomment-377226728

**Comment by yeomann** [comment]
friendly reminder: since issue is resolved, this thread should be closed!

**Comment by renestalder** [comment]
Honestly, I don't think switching back one major version is "resolving the issue". This problem still exists when used with the latest versions provided in the README.

**Comment by chandansutradhar2** [comment]
I am really frustrated with native script.  Ionic with all its short coming
is much better than ns
